FROM jenkins/jenkins:latest
#ARG path

USER root

RUN apt-get update && \
    apt-get install -y git docker.io curl && \
    rm -rf /var/lib/apt/lists/*

# RUN apt-get update && \
#     apt-get install -y curl iputils-ping docker.io && \
#     rm -rf /var/lib/apt/lists/* 

RUN usermod -aG 0 jenkins

RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && \
    chmod +x ./kubectl && \
    mv ./kubectl /usr/local/bin/kubectl

# RUN apt-get install -y iputils-ping && rm -rf /var/lib/apt/lists/*


# RUN touch /var/run/docker.sock
# RUN chmod 666 /var/run/docker.sock

USER jenkins



#CMD ["/bin/sh", "-c", "chmod 666 /var/run/docker.sock && su jenkins -c '/usr/bin/tini -- /usr/local/bin/jenkins.sh'"]

#CMD ["/bin/sh", "-c", "chmod 666 /var/run/docker.sock && /usr/bin/tini -- /usr/local/bin/jenkins.sh"]
