def gv

pipeline {
    agent any
    stages {
    
        stage('Setup Environment')
        {
            steps {
                script {
                    gv = load "${WORKSPACE}/Jenkins/script.groovy" 
                    
                    env.FRONTEND_IMAGE = "maxdev888/todo-list-app:frontend-"
                    env.BACKEND_IMAGE = "maxdev888/todo-list-app:backend-"
                    env.DATABASE_IMAGE = "maxdev888/todo-list-app:database-"
                    env.GITHUB_TOKEN = credentials('github-token')
                }}
        }

        stage('Build Images')
        {
            steps {
                script{
                    gv.buildImage()  
                }}
        }
          

        stage('Push to DockerHub')
        {
            steps {
                script{
                    gv.pushImage() 
                }}
        }
           

         stage('Update K8s Manifests')
        {
            steps {
                script{
                     gv.updateK8s() 
                }}
        }
            

         stage('Update GitHub Repo')
        {
            steps {
                script{
                        gv.githubPush()
                }}
        }
            

    }
}

